feat: Implement sub directory information
remyz17/odooghost pull request #25
Opened 2024-05-28 11:14 UTC by BonnetAdam

2024-05-29 12:25 UTC, BurkhalterY commented
lgtm

2024-06-15 20:28 UTC, BurkhalterY commented on exemples/full.yml
A better example could be found, as the repo odoo/odoo is built in loaded. 🤷

2024-06-19 23:42 UTC, remyz17 commented on exemples/full.yml
agree 

@BonnetAdam

2024-06-19 23:43 UTC, remyz17 requested changes
change example please

2024-06-22 21:18 UTC, BonnetAdam commented
Need improvement from my side

2024-06-22 21:18 UTC, closed without merging